language: node_js
node_js:
  - 0.10

install:
  - npm install grunt-cli
  - npm install bower
  - ./node_modules/.bin/bower install

script:
  - ./node_modules/.bin/grunt

deploy:
  provider: s3
  access_key_id: AKIAITO7NERWDHUB7PFA
  secret_access_key: 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
  bucket: cldsys-travis
  skip_cleanup: true
  upload-dir: travis-builds

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
  - node_modules
  - vendor
