language: node_js
node_js:
  - 0.10

install:
  - npm install grunt-cli
  - npm install bower
  - ./node_modules/.bin/bower install

script:
  - ./node_modules/.bin/grunt

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret_access_key: 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
    skip_cleanup: true
    bucket: cldsys-travis
    local-dir: archive
  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key: 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
    app-id: 3b308ab6-c407-4df9-850c-46f6c4eb04eb

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
  - node_modules
  - vendor
