language: php
php:
  - 5.5

install:
  - composer self-update
  - composer install --prefer-dist
  - ./bin/cloud doctrine:proxies:generate

script:
  - mkdir archive
  - zip -r archive/abc.zip . -x archive/ .git/ >/dev/null
  - zip -r archive/current.zip . -x archive/ .git/ >/dev/null

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: CyNd2eulxoaLZtC2wnJ+QaRJsoDQY3ol8++AnLIBFjISjSpe9AfsKgnbouaolGziT4KjyffyTwFxpkLWG3YykaawA1JD9+3GuielZ2oJW3P7dsw4NtnShVijHq+1/mQ0ORra2S1lHbBBuZ3eBLp2wLGwiW0WVLef8Ie4SbCozS4=
    skip_cleanup: true
    bucket: cldsys-travis
    local-dir: archive
    upload-dir: cloudxxx-api

  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: CyNd2eulxoaLZtC2wnJ+QaRJsoDQY3ol8++AnLIBFjISjSpe9AfsKgnbouaolGziT4KjyffyTwFxpkLWG3YykaawA1JD9+3GuielZ2oJW3P7dsw4NtnShVijHq+1/mQ0ORra2S1lHbBBuZ3eBLp2wLGwiW0WVLef8Ie4SbCozS4=
    app-id: 8f233699-7c36-4bcc-b94e-d8256b738fec
    wait-until-deployed: true

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  directories:
    - vendor

branches:
  only:
    - master
