language: node_js
node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret_access_key: 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
    bucket: cldsys-travis
    skip_cleanup: true
    upload-dir: travis-builds

  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key: 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
    app-id: 3b308ab6-c407-4df9-850c-46f6c4eb04eb
    skip_cleanup: true
    wait-until-deployed: true
