language: php
php:
  - 5.5

install:
  - composer self-update
  - composer install --prefer-dist

script:
  - mkdir archive
  - zip -r archive/abc.zip . -x archive/ .git/ >/dev/null
  - zip -r archive/current.zip . -x archive/ .git/ >/dev/null

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: FuBZzrE+9RS1Gj85EsH80FBh5xHQJK39v7vbFnEHgtVb2uS0+Rs0ZOQDWS2mr1s3KjOxs2V+ru1zn37zXOxGNQ54pfltfTiskWYDfK+tWYIzIE15Z1rFNWHO1syH9oCgUqK3QiBPcH+99BePWFEzFCK/ylM1SRqmSy9/GHam+mg=
    skip_cleanup: true
    bucket: cldsys-travis
    local-dir: archive
    upload-dir: cloudxxx-api

  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: FuBZzrE+9RS1Gj85EsH80FBh5xHQJK39v7vbFnEHgtVb2uS0+Rs0ZOQDWS2mr1s3KjOxs2V+ru1zn37zXOxGNQ54pfltfTiskWYDfK+tWYIzIE15Z1rFNWHO1syH9oCgUqK3QiBPcH+99BePWFEzFCK/ylM1SRqmSy9/GHam+mg=
    app-id: 8f233699-7c36-4bcc-b94e-d8256b738fec
    wait-until-deployed: true

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  directories:
    - vendor

branches:
  only:
    - master
