language: php
php:
  - 5.5

install:
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - hhvm /usr/local/bin/composer install --prefer-dist --no-dev --optimize-autoloader -vvv --profile

script:
  - ./bin/cloud doctrine:proxies:generate
  - mkdir archive
  - zip -r archive/abc.zip . -x archive/ .git/ >/dev/null
  - zip -r archive/current.zip . -x archive/ .git/ >/dev/null

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: CyNd2eulxoaLZtC2wnJ+QaRJsoDQY3ol8++AnLIBFjISjSpe9AfsKgnbouaolGziT4KjyffyTwFxpkLWG3YykaawA1JD9+3GuielZ2oJW3P7dsw4NtnShVijHq+1/mQ0ORra2S1lHbBBuZ3eBLp2wLGwiW0WVLef8Ie4SbCozS4=
    skip_cleanup: true
    bucket: cldsys-travis
    local-dir: archive
    upload-dir: cloudxxx-api
    on:
      branch: staging

  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key:
      secure: CyNd2eulxoaLZtC2wnJ+QaRJsoDQY3ol8++AnLIBFjISjSpe9AfsKgnbouaolGziT4KjyffyTwFxpkLWG3YykaawA1JD9+3GuielZ2oJW3P7dsw4NtnShVijHq+1/mQ0ORra2S1lHbBBuZ3eBLp2wLGwiW0WVLef8Ie4SbCozS4=
    app-id: 8f233699-7c36-4bcc-b94e-d8256b738fec
    wait-until-deployed: true
    on:
      branch: staging

  - provider: s3
    access_key_id: AKIAJGFXNYKXB75SIPGQ
    secret-access-key:
      secure: dunrkHjTJ7VNz4jPGL/DfgrncaEdDiMLIKIV32HoyXkPOjFZ9pOGnTztWdXhhF2MkwHEbE8MG/01PC9AYqAK+2EL0AiHjNRIDIpjKo2J4WuJjJemh4mqDR8ZmC0nwCbeJKatPWdqrdweaSgVYHbPg/TetRpjV37HOOBDbKonSKY=
    skip_cleanup: true
    bucket: cldsys-travis-prod
    local-dir: archive
    upload-dir: cloudxxx-api
    on:
      branch: prod

  - provider: opsworks
    access-key-id: AKIAJGFXNYKXB75SIPGQ
    secret-access-key:
      secure: dunrkHjTJ7VNz4jPGL/DfgrncaEdDiMLIKIV32HoyXkPOjFZ9pOGnTztWdXhhF2MkwHEbE8MG/01PC9AYqAK+2EL0AiHjNRIDIpjKo2J4WuJjJemh4mqDR8ZmC0nwCbeJKatPWdqrdweaSgVYHbPg/TetRpjV37HOOBDbKonSKY=
    app-id: 6dfb8967-9387-4be4-838d-d010fb6ea9e3
    wait-until-deployed: true
    on:
      branch: prod

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  directories:
    - vendor

branches:
  only:
    - staging
    - prod
