language: php
php:
  - 5.5

install:
  - composer self-update
  - composer install --prefer-dist

script:
  - mkdir archive
  - zip -r archive/abc.zip . -x archive/ .git/ >/dev/null
  - zip -r archive/current.zip . -x archive/ .git/ >/dev/null

deploy:
  - provider: s3
    access_key_id: AKIAITO7NERWDHUB7PFA
    secret_access_key: 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
    skip_cleanup: true
    bucket: cldsys-travis
    local-dir: archive
    upload-dir: cloudxxx-api

  - provider: opsworks
    access-key-id: AKIAITO7NERWDHUB7PFA
    secret-access-key: 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
    app-id: 8f233699-7c36-4bcc-b94e-d8256b738fec
    wait-until-deployed: true

env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  directories:
    - vendor
