FORMAT: 1A
HOST: http://api.tube.xxx

# tubexxx
tube.xxx API is a *video upload management* service for tube paysite webmasters.

## Video Collection [/v1/videos]
### List all Videos [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "We love candy"
        }, {
          "id": 2, "title": "Debbie does Chocolate"
        }]

### Create a Video [POST]
+ Request (application/json)

        { "title": "Chances and Tricks." }

+ Response 201 (application/json)

        { "id": 3, "title": "Chances and Tricks." }

## Video [/v1/videos/{id}]
A single video and it's metadata

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the video to get.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: Video

    + Body

            { "id": 2, "title": "Debbie does Chocolate" }

### Remove a Note [DELETE]
+ Response 204
